### ISSUE TITLE
/etc/dnsmasq.conf.include missing via skylark

### ISSUE THREAD

**Issue by haxwithaxe** [Byzantium/Byzantium#81] opened 2012-01-15 06:16 UTC
I ran dnsmasq --test

This returned cannot read /etc/dnsmasq.conf.include

I added a blank file: /etc/dnsmasq.conf.include

Now dnsmasq --test returns syntax check OK

**Comment by virtadpt** [comment] 2012-01-15 15:43
This is not a bug.

/etc/dnsmasq.conf.include is generated by the control panel when the network configuration information is generated.  It contains the A and RR records for all 254 IP addresses that node's copy of dnsmasqd is responsible for configuring and resolving.  When dnsmasqd starts at boottime it can't find that file and errors out - that is normal.  When the control panel configures everything, it starts dnsmasqd itself.

So, remove the empty /etc/dnsmasq.conf.include file you created.  In this respect things are as they should be.

**Closed as completed by virtadpt** 2012-01-15 15:43 UTC
Labels: System services
