### ISSUE TITLE
Reduce the amount of user interaction required to configure a node.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#153] opened 2012-07-22 01:18 UTC
While fairly easy to do, users still have to jump through a couple of hoops, er, pages, to configure a node.  Right now most users seem to go with the default values we set, so at least until we're in beta we can simplify things a lot by stripping most of those steps (i.e., calls to HTML templates) out, leaving the methods, and stepping through the methods one by one unitl the node is configured.

We can give the user something to look at by using some code from here: http://www.webappers.com/progressBar/ (thanks to FlyingKiwiGuy for the suggestion!)

**Comment by haxwithaxe** [comment] 2012-07-22 01:37
to summarize ...user actions:

<ol><li> insert CD/usb</li>
<li>boot</li>
<li>continue to use the laptop as if nothing were different (aside from the live distro)</li>
</ol>

note the lack of having to use the control panel if the defaults work.

this is step one toward grandma level usability :P

**Comment by SpartacusAU** [comment] 2012-07-27 15:02
Agree this needs to be changed. I find it quite confusing, perhaps some documentation on what is/should be happening here.

Especially between configure  network interfaces
and configure mesh network
Are these things different/part of the same process /or mutually exclusive. more prompts to say what to do in what order... 1 do this, etc

I had 2 nodes up today, one had working wired connection to internet but neither node could see the other with shell ping 192.168.x.y  the nodes were only 6 feet(2 meters) apart, separated by only air basically.
Both nodes had working wireless NIC's just to clarify. configured interfaces and configured to mesh.

System status page
The system  status data presentation needs to be changed.

mesh network interfaces info fields
it looks like a single line of text but is supposed to be broken into 3 fields. wider fields needed?

client network interfaces
it looks like a single line of text but is supposed to be broken into 2 fields. wider fields needed?
the number under number of associated client interfaces is so close to the IP address field it appears to be just a IP number ending in 0.
right adjust the number of associated clients field?

What is the PID for?

ESSID means? Encrypted?

Love the project, hope you can make it all work.

**Comment by Sitwon** [comment] 2012-08-25 23:45
dupe of #126

**Closed as completed by Sitwon** 2012-08-25 23:45 UTC
Labels: Control panel, ISO image - v0.3a
