### ISSUE TITLE
typos in build-final-module.sh and required_packages.txt

### ISSUE THREAD

**Issue by kg6gfq** [Byzantium/Byzantium#124] opened 2012-05-27 23:41 UTC
Line 4 of required_packages.txt is:
apr-1.4.2-i48**2**-2.xzm; should be
apr-1.4.2-i48**6**-2.xzm

Also, build-final-module.sh assumes the source is in 
/home/guest/**b**yzantium until line 30, after which it assumes 
/home/guest/**B**yzantium until the end of the file.  

build-final-module.sh line 77 is:
cp services.py /tmp/fakeroot/srv/httpd/cgi-bin; should be
cp services.py /tmp/fakeroot/srv/httpd/cgi-bin/

Before that line, though, should be:
mkdir /tmp/fakeroot/srv/httpd/cgi-bin

It looks like similar treatment is necessary for line 76:
cp index.html /tmp/fakeroot/srv/httpd/htdocs

I also had to comment out line 79:
rm /tmp/fakeroot/srv/httpd/cgi-bin/printenv /tmp/fakeroot/srv/httpd/cgi-bin
I don't know what that line is for, exactly - it seems to undo the previous section?

Line 137:
cp mop_up_dead_clients.py/tmp/fakeroot/usr/local/sbin needs a space in the middle.

(Apologies if this is not the best way to report this - I'm new to github.)

**Comment by Sitwon** [comment] 2012-05-28 03:16
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On Sun, 27 May 2012, kg6gfq wrote:

> Also, build-final-module.sh assumes the source is in
> /home/guest/**b**yzantium until line 30, after which it assumes
> /home/guest/**B**yzantium until the end of the file.

Your analysis is incorrect. We actualy have two separate repositories,
the Subversion respository where we keep large binaries (in particular
the compiled .xzm modules) and the Git repository where we keep the rest
of our source and scripts.

They are similarly named (and perhaps should be re-named to avoid this
confusion) but the subersion repository starts with 'b' and the Git
repository starts with 'B'. On Linux most filesystems are case-sensitive
and allow for both directories to exist independently of each other.

> build-final-module.sh line 77 is:
> cp services.py /tmp/fakeroot/srv/httpd/cgi-bin; should be
> cp services.py /tmp/fakeroot/srv/httpd/cgi-bin/

If 'cgi-bin' exists and is a directory then the trailing '/' is implied.

> Before that line, though, should be:
> mkdir /tmp/fakeroot/srv/httpd/cgi-bin

This is the real problem. I will double-check this part.

> It looks like similar treatment is necessary for line 76:
> cp index.html /tmp/fakeroot/srv/httpd/htdocs

This as well.

> I also had to comment out line 79:
> rm /tmp/fakeroot/srv/httpd/cgi-bin/printenv /tmp/fakeroot/srv/httpd/cgi-bin
> I don't know what that line is for, exactly - it seems to undo the previous section?

I am confused as well. Did I write that part?

> Line 137:
> cp mop_up_dead_clients.py/tmp/fakeroot/usr/local/sbin needs a space in the middle.

Yes, it does.

> (Apologies if this is not the best way to report this - I'm new to github.)

This is fine. You gave us enough detail and clarity to identify and
address the issues. It would be easiest for us if you made the changes
in your fork and submitted them to us as a Pull Request, but I'm not one
to look a gift horse in the mouth.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJPwu4KAAoJEMco5sYyM+0w1AAIAJ0oTm+9YLdWECd/M6YbnSUi
mmPlzVDhxVAfhbpPbkPP2hQMK+zDeHkggGwnsgjzUihcq1o9MXj4ZQe0w65CiJip
CYls2NSVnih5DBoSZMMJDncBbmAPKhqhY6hbd5+EtMOOEOQLqxAtPIyKduwjUzui
bb8igqJW1+SfV5SJpdqzRrJMlCsjA+j1kVQVDyjaYEDOdGXTi1H5xOf53MdIqhbm
Jq5mfXZf3K5YwmjbltYJZJLPfuZgEcE61YC/L36OyomXHEhATcx6ffE+beTVB5rC
53i6Vwtn/Lax5HBPX4Ld6fw98dE3p2KuxywhFROsGGcB5CMneBe6Ek9NysWlkZY=
=pw9Q
-----END PGP SIGNATURE-----

**Comment by Sitwon** [comment] 2012-05-28 03:21
The problems on lines 73-79 seem to be The Doctor's work (according to 'git blame').

Doc: What's the deal? What was intended there?

**Comment by virtadpt** [comment] 2012-06-03 18:40
Cutting and pasting my e-mails to the list into this ticket because I didn't realize that I didn't reply to Github.

> Line 4 of required_packages.txt is: apr-1.4.2-i48**2**-2.xzm;
> should be apr-1.4.2-i48**6**-2.xzm

Fixed - will check new version in after I send this message.

> Also, build-final-module.sh assumes the source is in
> /home/guest/**b**yzantium until line 30, after which it assumes
> /home/guest/**B**yzantium until the end of the file.

Not a bug.  ~guest/byzantium/ is the SVN repo of .xzm packages.  In
that part of the script, the ones in required_packages.txt are
unpacked into a fakeroot.  The script then switches to
~guest/Byzantium/, which is a checkout of the Git repository.

> build-final-module.sh line 77 is: cp services.py
> /tmp/fakeroot/srv/httpd/cgi-bin; should be cp services.py
> /tmp/fakeroot/srv/httpd/cgi-bin/

I see no semicolon here.

I just did a `git pull` to update my local repo -
build-final-module.sh didn't change.  Visual inspection confirms no
semicolon.  What's the hash and timestamp on your copy of the script?

> Before that line, though, should be: mkdir
> /tmp/fakeroot/srv/httpd/cgi-bin

That directory exists by default in Slackware's httpd package.

> It looks like similar treatment is necessary for line 76: cp
> index.html /tmp/fakeroot/srv/httpd/htdocs

Same.

> I also had to comment out line 79: rm
> /tmp/fakeroot/srv/httpd/cgi-bin/printenv
> /tmp/fakeroot/srv/httpd/cgi-bin I don't know what that line is for,
> exactly - it seems to undo the previous section?

That's a bug but not in that particular way.

There are two default cgi-bin scripts in /srv/httpd/cgi-bin/ -
printenv and test-cgi.  It's good practice to remove the demo scripts
if they don't need to be in there.  The bug is that I forgot to finish
that particular line.

Fixed.

> Line 137: cp mop_up_dead_clients.py/tmp/fakeroot/usr/local/sbin
> needs a space in the middle.

Oops.  Fixed.

> (Apologies if this is not the best way to report this - I'm new to
> github.)

Nope, that's perfect.  Thank you!

These bugs are fixed in commit d8ba603ce69459bf80a04e651bc6b2795853c341.

**Closed as completed by virtadpt** 2012-06-03 18:40 UTC
