### ISSUE TITLE
Setting up encryption on wireless gateway interfaces needs to be possible.

### ISSUE THREAD

**Issue by virtadpt** [Byzantium/Byzantium#65] opened 2011-11-19 21:25 UTC
This is actually a show stopper at home for testing.

It needs to be possible to configure encryption on wireless interfaces that need it.  It isn't a reasonable assumption that wireless access points will not have encryption set on them, and in fact in reality the opposite is true.  Doubly so in scenarios derived from the Egypt Problem in which wireless access points are being hunted down and their operators apprehended.

The problem here is that it's easy to configure WEP on a wireless interface with iwconfig, but nontrivial to configure WPA(2).  wpa_supplicant is required for that, and it's not actually easy to manipulate.

What we do have is wicd running on every Byzantium node by default because it's part of Porteus Linux.  It's written in Python.  I think it might be possible to import it as a module into gateways.py and use it to configure encryption on wireless gateway interfaces.

**Comment by virtadpt** [comment] 2011-11-22 14:36
wicd has a nifty unprivileged client/privileged server architecture for configuring network interfaces.  This is good.  They communicate with one another using DBUS which will drive you crazy until you figure it out (kind of like antenna theory).  Each client has to have its own DBUS code, there are no modules of shared utility code or anything like that, it's done from scratch each time.  This is bad.

However, wicd includes a command-line client called wicd-cli, which will do exactly what we need, which is configuring encryption on wireless network interfaces.  I've been toying with it and it can be used to not only set up the proper layer 1 and layer 2 stuff on an interface, but it will also automagically generate a configuration file suitable for use with wpa_supplicant if necessary.  I've documented much of the procedure but don't have it with me at the moment.  When I put it into the Byzantium wiki I'll link to it.

**Comment by virtadpt** [comment] 2011-12-09 17:18
Official notes on the use of wicd-cli from the dev branch of wicd: http://bazaar.launchpad.net/~wicd-devel/wicd/experimental/view/head:/cli/README.cli

**Comment by Sitwon** [comment] 2012-08-25 22:45
This is a dupe of #32.

**Closed as completed by Sitwon** 2012-08-25 22:45 UTC
Labels: Control panel, Feature request, Request for comments
